version: "3"  
services:
  api:
    build: ./api
    container_name: api_c
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app
  sys-stats:
    build: ./sys-stats
    container_name: sys-stats
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true


